import { test, expect, chatTitle, documentTitle } from './fixtures'
import {
  box, hideNavigation, inViewport, isPhone, loadLibrary, moveReader, noBodyOverflow,
  openDocument, openQuiz, reopenQuiz, screenshot, scrollInnerKeepingChrome, showNavigation,
} from './helpers'

test.beforeEach(async ({ page }) => { await loadLibrary(page) })

test('library actions align with their rows and the body stays within the viewport', async ({ page }, testInfo) => {
  await noBodyOverflow(page)
  await inViewport(page.locator('.library-actions'), page)
  const clear = await box(page.getByRole('button', { name: 'Clear library', exact: true }))
  const upload = await box(page.locator('.library-upload'))
  // Both actions may wrap as a group on narrow screens, but never overlap.
  expect(clear.x + clear.width <= upload.x + 1 || clear.y + clear.height <= upload.y + 1).toBeTruthy()
  const rightEdges: number[] = []
  for (const row of await page.locator('.library-item').all()) {
    const content = await box(row.locator('.library-row'))
    const action = await box(row.locator('.library-delete'))
    await inViewport(row.locator('.library-delete'), page)
    expect(action.x).toBeGreaterThanOrEqual(content.x + content.width)
    expect(Math.abs(action.y + action.height / 2 - content.y - content.height / 2)).toBeLessThanOrEqual(1)
    rightEdges.push(action.x + action.width)
  }
  expect(Math.abs(rightEdges[0]! - rightEdges[1]!)).toBeLessThanOrEqual(1)
  await screenshot(page, testInfo, 'library-alignment')
})

test('chat options support right-click, visible ellipsis, keyboard navigation and Escape focus', async ({ page }, testInfo) => {
  await showNavigation(page)
  const trigger = page.getByRole('button', { name: `Options for ${chatTitle}`, exact: true })
  await inViewport(trigger, page)
  await expect(trigger).toHaveCSS('opacity', '1')
  await expect(trigger.locator('svg')).toBeVisible()
  await page.locator('.chat-history-row').filter({ hasText: chatTitle }).click({ button: 'right' })
  const menu = page.getByRole('dialog', { name: 'Saved chat options' })
  await inViewport(menu, page)
  await expect(page.getByRole('menuitem', { name: 'Open chat', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Delete chat', exact: true })).toBeFocused()
  await screenshot(page, testInfo, 'chat-context-menu')
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.press('Shift+F10')
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('failed DELETE closes confirmation and shows a dismissible floating snackbar', async ({ page, mockApi }, testInfo) => {
  mockApi.failDeletes = true
  await showNavigation(page)
  const trigger = page.getByRole('button', { name: `Options for ${chatTitle}`, exact: true })
  await trigger.click()
  await page.getByRole('menuitem', { name: 'Delete chat', exact: true }).click()
  const dialog = page.getByRole('alertdialog', { name: 'Delete this chat?' })
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  expect(mockApi.callsFor('DELETE', '/conversations/11')).toHaveLength(0)
  await dialog.getByRole('button', { name: 'Delete chat', exact: true }).click()
  const error = page.getByRole('alert')
  await expect(error).toContainText('Mock deletion failed. Nothing was removed.')
  await expect(dialog).not.toBeVisible()
  await inViewport(error, page)
  expect(await page.locator('.toast-stack').evaluate(element => element.matches(':popover-open'))).toBe(true)
  const dismiss = page.getByRole('button', { name: 'Dismiss error', exact: true })
  await screenshot(page, testInfo, 'delete-error-over-modal')
  await dismiss.click()
  await expect(error).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await expect(page.locator('.chat-history-row')).toHaveCount(3)
  expect(mockApi.callsFor('DELETE', '/conversations/11')).toHaveLength(1)
  expect(mockApi.conversations).toHaveLength(3)
})

for (const kind of ['chat', 'document', 'history', 'library'] as const) {
  test(`successful mocked ${kind} cleanup removes only the intended data`, async ({ page, mockApi }) => {
    const settings = {
      chat: { path: '/conversations/11', title: 'Delete this chat?', action: 'Delete chat', notice: 'Chat deleted.', docs: 2, chats: 2 },
      document: { path: '/documents/1', title: 'Delete this PDF?', action: 'Delete PDF', notice: 'PDF deleted.', docs: 1, chats: 1 },
      history: { path: '/conversations', title: 'Clear chat history?', action: 'Clear history', notice: 'Chat history cleared.', docs: 2, chats: 0 },
      library: { path: '/documents', title: 'Clear your library?', action: 'Clear library', notice: 'Library cleared.', docs: 0, chats: 0 },
    }[kind]
    // Delete the active conversation/history as well as checking saved lists.
    if (kind === 'chat' || kind === 'history') {
      await showNavigation(page)
      await page.locator('.chat-history-row').getByRole('button', { name: chatTitle, exact: true }).click()
      await expect(page.locator('.messages .message')).toHaveCount(16)
      if (isPhone(page)) await page.getByRole('button', { name: 'Close study tools', exact: true }).click()
      await showNavigation(page)
      if (kind === 'chat') {
        await page.getByRole('button', { name: `Options for ${chatTitle}`, exact: true }).click()
        await page.getByRole('menuitem', { name: 'Delete chat', exact: true }).click()
      } else await page.getByRole('button', { name: 'Clear chat history', exact: true }).click()
    } else if (kind === 'document') await page.getByRole('button', { name: `Delete ${documentTitle}`, exact: true }).click()
    else await page.getByRole('button', { name: 'Clear library', exact: true }).click()
    const dialog = page.getByRole('alertdialog', { name: settings.title })
    await expect(dialog).toBeVisible()
    expect(mockApi.callsFor('DELETE', settings.path)).toHaveLength(0)
    await dialog.getByRole('button', { name: settings.action, exact: true }).click()
    await expect(dialog).not.toBeVisible()
    await expect(page.locator('.notice-toast')).toContainText(settings.notice)
    await expect(page.locator('.chat-history-row')).toHaveCount(settings.chats)
    expect(mockApi.callsFor('DELETE', settings.path)).toHaveLength(1)
    expect(mockApi.documents).toHaveLength(settings.docs)
    expect(mockApi.conversations).toHaveLength(settings.chats)
    if (kind === 'chat' || kind === 'history') {
      await hideNavigation(page)
      if (isPhone(page)) await page.getByRole('button', { name: 'Open study tools', exact: true }).click()
      await expect(page.locator('.messages .message')).toHaveCount(0)
      await expect(page.locator('.chat-empty')).toBeVisible()
      if (isPhone(page)) await page.getByRole('button', { name: 'Close study tools', exact: true }).click()
      await page.getByRole('button', { name: 'Back to My library', exact: true }).click()
    }
    await expect(page.locator('.library-item')).toHaveCount(settings.docs)
    if (kind === 'document') await expect(page.locator('.library-row')).toContainText('Networks and distributed systems')
    if (kind === 'library') await expect(page.getByRole('heading', { name: 'No PDFs yet' })).toBeVisible()
    // A fresh UI load still reflects the mutable mock store, not stale Vue state.
    await page.reload()
    await expect(page.getByRole('heading', { name: 'My library', exact: true })).toBeVisible()
    await expect(page.locator('.library-item')).toHaveCount(settings.docs)
    await expect(page.locator('.chat-history-row')).toHaveCount(settings.chats)
  })
}

test('quiz defaults to the navigated page; an explicit selection survives reader changes', async ({ page, mockApi }) => {
  await openDocument(page)
  await moveReader(page)
  await expect(page.locator('.pdf h2')).toHaveText('Page 2')
  await openQuiz(page)
  await expect(page.locator('.quiz-source')).toHaveText('Source Page 2')
  await page.getByRole('button', { name: 'Start 10 questions' }).click()
  await expect(page.locator('.quiz-index')).toHaveCount(10)
  expect(mockApi.callsFor('POST', '/documents/1/quiz').map(call => call.body)).toEqual([{ page_numbers: [2], question_count: 10 }])
  await page.getByRole('button', { name: 'Change pages' }).click()
  const picker = page.getByRole('dialog', { name: 'Choose your source pages' })
  await picker.getByRole('button', { name: 'Clear', exact: true }).click()
  await picker.getByRole('checkbox', { name: 'Page 1', exact: true }).check()
  await picker.getByRole('checkbox', { name: 'Page 3', exact: true }).check()
  await picker.getByRole('button', { name: 'Apply pages' }).click()
  await expect(page.locator('.quiz-source')).toHaveText('Source Pages 1, 3')
  await expect(page.getByRole('button', { name: 'Start 10 questions' })).toBeVisible()
  await moveReader(page)
  await expect(page.locator('.pdf h2')).toHaveText('Page 3')
  if (page.viewportSize()!.width <= 900) await reopenQuiz(page)
  await expect(page.locator('.quiz-source')).toHaveText('Source Pages 1, 3')
  await page.getByRole('button', { name: 'Start 10 questions' }).click()
  await expect(page.locator('.quiz-index')).toHaveCount(10)
  expect(mockApi.callsFor('POST', '/documents/1/quiz').map(call => call.body)).toEqual([
    { page_numbers: [2], question_count: 10 }, { page_numbers: [1, 3], question_count: 10 },
  ])
})

test('ten-question practice retains state and scores revealed, wrong and unanswered responses correctly', async ({ page, mockApi }, testInfo) => {
  await openDocument(page)
  await openQuiz(page)
  await page.getByRole('button', { name: 'Start 10 questions' }).click()
  const quiz = page.locator('.quiz-panel')
  await expect(quiz.getByRole('navigation', { name: 'Quiz questions' }).getByRole('button')).toHaveCount(10)
  await quiz.getByRole('radio').nth(0).check()
  await expect(quiz.getByRole('radio').nth(0)).toBeChecked()
  await quiz.getByRole('button', { name: 'Show answer', exact: true }).click()
  const reveal = page.getByRole('dialog', { name: 'See the reasoning first?' })
  await expect(reveal).toContainText('even if your selected answer is correct')
  await reveal.getByRole('button', { name: 'Reveal answer', exact: true }).click()
  await expect(quiz.getByRole('radio').nth(0)).toBeDisabled()
  await expect(quiz.getByRole('button', { name: 'Question 1: Revealed, no credit', exact: true })).toBeVisible()
  await quiz.getByRole('button', { name: 'Next', exact: true }).click()
  await quiz.getByRole('radio').nth(0).check()
  await quiz.getByRole('button', { name: 'Next', exact: true }).click()
  await quiz.getByRole('radio').nth(1).check()
  await expect(quiz.locator('.quiz-progress-copy')).toContainText('3 / 10 answered')
  if (page.viewportSize()!.width <= 900) await page.getByRole('button', { name: 'Close study tools', exact: true }).click()
  else await page.getByRole('button', { name: 'Hide tools', exact: true }).click()
  await expect(quiz).not.toBeVisible()
  await reopenQuiz(page)
  await expect(quiz.getByRole('button', { name: 'Question 3: Answered', exact: true })).toHaveAttribute('aria-current', 'step')
  await expect(quiz.getByRole('radio').nth(1)).toBeChecked()
  await page.locator('.tabs').getByRole('button', { name: 'Text', exact: true }).click()
  await page.locator('.tabs').getByRole('button', { name: 'Check Me', exact: true }).click()
  await expect(quiz.getByRole('radio').nth(1)).toBeChecked()
  expect(mockApi.callsFor('POST', '/documents/1/quiz')).toHaveLength(1)
  await quiz.getByRole('button', { name: 'Submit practice' }).click()
  const submit = page.getByRole('dialog', { name: 'Submit with unanswered questions?' })
  await expect(submit).toContainText('7 questions are unanswered')
  await submit.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(quiz.locator('.quiz-progress-copy')).toContainText('3 / 10 answered')
  await quiz.getByRole('button', { name: 'Submit practice' }).click()
  await submit.getByRole('button', { name: 'Submit anyway', exact: true }).click()
  await expect(quiz.locator('.quiz-progress-copy')).toContainText('1 / 10 earned')
  await expect(quiz.getByRole('progressbar', { name: 'Earned score' })).toHaveAttribute('value', '1')
  await expect(quiz.getByRole('button', { name: 'Question 1: Revealed, no credit', exact: true })).toBeVisible()
  await expect(quiz.getByRole('button', { name: 'Question 2: Correct', exact: true })).toBeVisible()
  await expect(quiz.getByRole('button', { name: 'Question 3: Needs revision', exact: true })).toBeVisible()
  await quiz.getByRole('button', { name: 'Question 4: Unanswered', exact: true }).click()
  await expect(quiz.getByRole('radio').nth(0)).toBeDisabled()
  await expect(quiz.getByRole('heading', { name: 'Why this answer works' })).toBeAttached()
  await screenshot(page, testInfo, 'quiz-incomplete-review')
})

test('PDF and quiz scroll internally while their headers and footers stay in place', async ({ page }, testInfo) => {
  await openDocument(page)
  const readerChrome = isPhone(page)
    ? [page.locator('.shell main > header'), page.locator('.mobile-reader-dock')]
    : [page.locator('.shell main > header'), page.locator('.reader-bar'), page.locator('.paginate')]
  await scrollInnerKeepingChrome(page, page.locator('.pdf'), readerChrome)
  await openQuiz(page)
  await page.getByRole('button', { name: 'Start 10 questions' }).click()
  await page.getByRole('button', { name: 'Show answer', exact: true }).click()
  await page.getByRole('dialog', { name: 'See the reasoning first?' }).getByRole('button', { name: 'Reveal answer', exact: true }).click()
  await scrollInnerKeepingChrome(page, page.locator('.quiz-body'), [page.locator('.quiz-header'), page.locator('.quiz-footer')])
  await expect(page.getByRole('button', { name: 'Revisit page 1', exact: true })).toBeInViewport()
  await screenshot(page, testInfo, 'quiz-inner-scroll')
})

test('chat keeps its composer fixed; Shift+Enter inserts a newline and Enter sends once', async ({ page, mockApi }, testInfo) => {
  await showNavigation(page)
  await page.locator('.chat-history-row').getByRole('button', { name: chatTitle, exact: true }).click()
  await expect(page.locator('.messages .message')).toHaveCount(16)
  await scrollInnerKeepingChrome(page, page.locator('.messages'), [page.locator('.chat-content .head'), page.locator('.composer')])
  const input = page.getByRole('textbox', { name: 'Message about this document', exact: true })
  await input.fill('First line')
  await input.press('Shift+Enter')
  await expect(input).toHaveValue('First line\n')
  expect(mockApi.callsFor('POST', '/chat')).toHaveLength(0)
  await input.press('x')
  await input.press('Enter')
  await expect(page.locator('.messages .message')).toHaveCount(18)
  await expect(input).toHaveValue('')
  expect(mockApi.callsFor('POST', '/chat').map(call => call.body)).toEqual([
    { content: 'First line\nx', document_id: 1, conversation_id: 11 },
  ])
  await expect(page.locator('.message.assistant').last()).toHaveText('Mock reply: First line\nx')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled()
  await input.press('Enter')
  await expect(input).toHaveValue('')
  expect(mockApi.callsFor('POST', '/chat')).toHaveLength(1)
  await noBodyOverflow(page)
  await screenshot(page, testInfo, 'chat-multiline-send')
})