<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { AlertCircle, ArrowLeft, BookOpen, BrainCircuit, ChevronLeft, ChevronRight, FileText, History, Languages, LibraryBig, LogOut, Menu, MessageSquare, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, Pause, Play, Plus, RotateCcw, Search, Send, Sparkles, Upload, Volume2, X, ZoomIn, ZoomOut } from '@lucide/vue'
import { api, type Conversation, type DocumentDetail, type DocumentSummary, type Message, type User } from './api'

type Tab = 'text' | 'summary' | 'translate' | 'study' | 'chat'
type MobileSheet = 'pages' | 'tools' | null
const user = ref<User | null>(null), documents = ref<DocumentSummary[]>([]), chats = ref<Conversation[]>([]), document = ref<DocumentDetail | null>(null)
const messages = ref<Message[]>([]), tab = ref<Tab>('text'), page = ref(1), reading = ref(false), sidebar = ref(false), navCollapsed = ref(false), thumbnailsOpen = ref(true), toolsOpen = ref(true), language = ref('Luganda')
const mobileSheet = ref<MobileSheet>(null)
const pdfZoom = ref(100), toolsWidth = ref(440)
const username = ref(''), password = ref(''), authMode = ref<'login'|'register'>('login'), error = ref(''), busy = ref(false), prompt = ref(''), conversationId = ref<number|null>(null)
const summaryPrompt = ref(''), summaryResult = ref(''), translationResult = ref(''), studyQuestion = ref(''), studyAnswer = ref(''), studyFeedback = ref(''), toolBusy = ref(false)
const searchOpen = ref(false), searchQuery = ref(''), searchInput = ref<HTMLInputElement | null>(null)
const errorToast = ref('')
let errorToastTimer: ReturnType<typeof setTimeout> | undefined
let documentRequest = 0
let overlayTrigger: HTMLElement | null = null
const currentText = computed(() => document.value?.pages.find(item => item.page_number === page.value)?.text || 'No extractable text was found on this page.')
const normalizedSearch = computed(() => searchQuery.value.trim().toLowerCase())
const searchedDocuments = computed(() => normalizedSearch.value ? documents.value.filter(item => `${item.title} ${item.filename}`.toLowerCase().includes(normalizedSearch.value)) : documents.value.slice(0, 5))
const searchedChats = computed(() => normalizedSearch.value ? chats.value.filter(item => item.title.toLowerCase().includes(normalizedSearch.value)) : chats.value.slice(0, 5))
const searchedPages = computed(() => !normalizedSearch.value || !document.value ? [] : document.value.pages.filter(item => item.text.toLowerCase().includes(normalizedSearch.value)).slice(0, 10))

async function refreshHistory() { documents.value = await api('/documents'); chats.value = await api('/conversations') }
async function authenticate() { busy.value=true; error.value=''; try { user.value=await api(`/auth/${authMode.value}`,{method:'POST',body:JSON.stringify({username:username.value,password:password.value})}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function logout() { await api('/auth/logout',{method:'POST'}); user.value=null; document.value=null }
function resetPageTools() { summaryResult.value=''; translationResult.value=''; studyQuestion.value=''; studyAnswer.value=''; studyFeedback.value='' }
function closeDocument() { documentRequest++; mobileSheet.value=null; speechSynthesis.cancel(); reading.value=false; document.value=null; conversationId.value=null; messages.value=[]; resetPageTools() }
async function openDocument(id:number) { const request=++documentRequest; error.value=''; try { const selected=await api<DocumentDetail>(`/documents/${id}`); if(request!==documentRequest)return; document.value=selected; page.value=1; tab.value='text'; mobileSheet.value=null; conversationId.value=null; messages.value=[]; resetPageTools(); sidebar.value=false } catch(e) { if(request===documentRequest) error.value=(e as Error).message } }
async function upload(event:Event) { const file=(event.target as HTMLInputElement).files?.[0]; if(!file)return; busy.value=true; error.value=''; try { const data=new FormData(); data.append('file',file); const created=await api<DocumentSummary>('/documents',{method:'POST',body:data}); await refreshHistory(); await openDocument(created.id) } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function openChat(id:number) { const result=await api<{id:number;title:string;messages:Message[]}>(`/conversations/${id}`); const history=chats.value.find(item=>item.id===id); if(history?.document_id) await openDocument(history.document_id); conversationId.value=id; messages.value=result.messages; tab.value='chat'; sidebar.value=false }
async function send() { if(!prompt.value.trim())return; const content=prompt.value; messages.value.push({role:'user',content}); prompt.value=''; busy.value=true; try { const result=await api<{conversation_id:number;reply:string}>('/chat',{method:'POST',body:JSON.stringify({content,document_id:document.value?.id,conversation_id:conversationId.value})}); conversationId.value=result.conversation_id; messages.value.push({role:'assistant',content:result.reply}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function pageRequest(content:string) { if(!document.value) throw new Error('Open a document first'); const result=await api<{conversation_id:number;reply:string}>('/chat',{method:'POST',body:JSON.stringify({content,document_id:document.value.id,page_number:page.value})}); await refreshHistory(); return result.reply }
async function summarizePage() { toolBusy.value=true; error.value=''; try { summaryResult.value=await pageRequest(`Summarize only this page${summaryPrompt.value.trim()?` with this focus: ${summaryPrompt.value.trim()}`:''}. Give a concise heading and 3 to 5 key points.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function translatePage() { toolBusy.value=true; error.value=''; try { translationResult.value=await pageRequest(`Translate only this page into ${language.value}. Preserve meaning and formatting. Return only the translation.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function startStudy() { tab.value='study'; toolsOpen.value=true; mobileSheet.value='tools'; toolBusy.value=true; studyFeedback.value=''; studyAnswer.value=''; try { studyQuestion.value=await pageRequest('Create one recall question using only this page. Return only the question and do not reveal the answer.') } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function checkStudyAnswer() { if(!studyAnswer.value.trim())return; toolBusy.value=true; try { studyFeedback.value=await pageRequest(`Question: ${studyQuestion.value}\nStudent answer: ${studyAnswer.value}\nEvaluate using only this page. Give a score out of 100, correct points, missing points, and a concise improvement.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
function speak() { if(reading.value){speechSynthesis.cancel();reading.value=false;return} const utterance=new SpeechSynthesisUtterance(currentText.value); utterance.onend=()=>{reading.value=false;if(document.value&&page.value<document.value.page_count){page.value++;speak()}}; reading.value=true;speechSynthesis.speak(utterance) }
function selectPage(nextPage:number){page.value=nextPage;closeMobileSheet();resetPageTools()}
function move(by:number){if(document.value)selectPage(Math.min(document.value.page_count,Math.max(1,page.value+by)))}
function changeZoom(by:number) { pdfZoom.value=Math.min(160,Math.max(75,pdfZoom.value+by)) }
function toggleNavigation() { navCollapsed.value=!navCollapsed.value; if(navCollapsed.value) toolsOpen.value=true }
async function openMobileSheet(nextSheet:Exclude<MobileSheet,null>) { overlayTrigger=globalThis.document.activeElement as HTMLElement; mobileSheet.value=nextSheet; await nextTick(); globalThis.document.querySelector<HTMLElement>('[role="dialog"] button')?.focus() }
function closeMobileSheet() { const trigger=overlayTrigger; mobileSheet.value=null; nextTick(()=>trigger?.focus()) }
function openMobileTools(nextTab:Tab=tab.value) { tab.value=nextTab; toolsOpen.value=true; void openMobileSheet('tools') }
function closeTools() { closeMobileSheet(); toolsOpen.value=false }
async function openNavigation() { overlayTrigger=globalThis.document.activeElement as HTMLElement; sidebar.value=true; await nextTick(); globalThis.document.querySelector<HTMLElement>('.sidebar .close')?.focus() }
function closeNavigation() { sidebar.value=false; nextTick(()=>overlayTrigger?.focus()) }
function closeOverlaysOnEscape(event:KeyboardEvent) { if(event.key!=='Escape')return; if(mobileSheet.value)closeMobileSheet(); if(sidebar.value)closeNavigation() }
async function showSearch() { searchOpen.value=true; await nextTick(); searchInput.value?.focus() }
function closeSearch() { searchOpen.value=false; searchQuery.value='' }
async function openSearchDocument(id:number) { await openDocument(id); closeSearch() }
function openSearchPage(pageNumber:number) { selectPage(pageNumber); closeSearch() }
function resizePane(pane:'nav'|'tools', event:PointerEvent) {
  if (innerWidth <= 900) return
  const root = globalThis.document.documentElement
  const startX = event.clientX
  const property = pane === 'nav' ? '--nav-width' : '--tools-width'
  const current = pane==='tools' ? toolsWidth.value : Number.parseFloat(getComputedStyle(root).getPropertyValue(property))
  const minimum = pane === 'nav' ? 190 : 300
  const maximum = pane === 'nav' ? 360 : 600
  if (pane === 'nav') navCollapsed.value=false
  const movePointer = (moveEvent:PointerEvent) => {
    const delta = pane === 'nav' ? moveEvent.clientX-startX : startX-moveEvent.clientX
    const width=Math.min(maximum,Math.max(minimum,current+delta))
    if(pane==='tools') toolsWidth.value=width
    else root.style.setProperty(property, `${width}px`)
  }
  const stopPointer = () => { removeEventListener('pointermove',movePointer); removeEventListener('pointerup',stopPointer) }
  addEventListener('pointermove',movePointer)
  addEventListener('pointerup',stopPointer,{once:true})
}
function resizePaneByKey(pane:'nav'|'tools', direction:number) {
  const root=globalThis.document.documentElement, property=pane==='nav'?'--nav-width':'--tools-width'
  const current=pane==='tools' ? toolsWidth.value : Number.parseFloat(getComputedStyle(root).getPropertyValue(property))
  const width=Math.min(pane==='nav'?360:600,Math.max(pane==='nav'?190:300,current+direction*16))
  if(pane==='tools') toolsWidth.value=width
  else root.style.setProperty(property,`${width}px`)
}
function formatDocumentDate(value:string) { return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)) }
function dismissError() { errorToast.value=''; if(errorToastTimer) clearTimeout(errorToastTimer) }
watch(error, value => {
  if(!value) return
  errorToast.value=value
  if(errorToastTimer) clearTimeout(errorToastTimer)
  errorToastTimer=setTimeout(()=>errorToast.value='',6000)
})
onMounted(async()=>{globalThis.document.addEventListener('keydown',closeOverlaysOnEscape);try{user.value=await api('/auth/me');await refreshHistory()}catch{user.value=null}})
onBeforeUnmount(()=>globalThis.document.removeEventListener('keydown',closeOverlaysOnEscape))
</script>

<template>
  <div class="app-root">
  <Transition name="toast"><aside v-if="errorToast" class="error-toast" role="alert" aria-live="assertive"><AlertCircle :size="20"/><div><strong>Something went wrong</strong><p>{{errorToast}}</p></div><button aria-label="Dismiss error" @click="dismissError"><X :size="17"/></button></aside></Transition>
  <section v-if="!user" class="auth-page"><form class="auth-box" @submit.prevent="authenticate"><div class="auth-brand"><b><BookOpen :size="22" /></b> edutool</div><p class="eyebrow">YOUR STUDY WORKSPACE</p><h1>{{authMode==='login'?'Welcome back':'Create your account'}}</h1><label>Username<input v-model="username" required minlength="3" autocomplete="username"></label><label>Password<input v-model="password" required minlength="8" type="password" autocomplete="current-password"></label><p v-if="error" class="error">{{error}}</p><button class="button primary auth-submit" :disabled="busy">{{busy?'Please wait…':authMode==='login'?'Sign in':'Register'}}</button><button type="button" class="auth-switch" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'New here? Create an account':'Already registered? Sign in'}}</button></form></section>
  <div v-else class="shell" :class="{'nav-collapsed':navCollapsed,'document-open':document}">
    <aside class="sidebar" :class="{open:sidebar}" aria-label="Document library" @keydown.esc="closeNavigation">
      <div class="brand"><b><BookOpen :size="20" /></b><span>edutool</span><button class="close" aria-label="Close navigation" @click="closeNavigation"><X :size="19" /></button></div>
      <label class="upload-button"><Upload :size="17" /><span>{{busy?'Processing…':'Upload PDF'}}</span><input type="file" accept="application/pdf" :disabled="busy" @change="upload"></label>
      <nav><p class="nav-title"><LibraryBig :size="14" /><span>RECENT DOCUMENTS</span></p><button v-for="item in documents.slice(0,5)" :key="item.id" :title="item.title" :class="{active:item.id===document?.id}" :aria-current="item.id===document?.id?'page':undefined" @click="openDocument(item.id)"><FileText :size="17" /><span>{{item.title}}<small>{{item.page_count}} pages</small></span></button><p v-if="!documents.length" class="empty-nav">Upload your first PDF</p><p class="nav-title history-title"><History :size="14" /><span>CHAT HISTORY</span></p><button v-for="chat in chats" :key="chat.id" :title="chat.title" @click="openChat(chat.id)"><MessageSquare :size="17" /><span>{{chat.title}}</span></button><p v-if="!chats.length" class="empty-nav">No conversations yet</p></nav>
      <nav class="bottom"><button title="Sign out" @click="logout"><LogOut :size="17" /><span>Sign out</span></button><div class="profile"><i>{{user.username.slice(0,2).toUpperCase()}}</i><span><strong>{{user.username}}</strong><small>Student workspace</small></span></div></nav>
      <div class="pane-resizer nav-resizer" role="separator" aria-label="Resize navigation" tabindex="0" @pointerdown="resizePane('nav',$event)" @keydown.left.prevent="resizePaneByKey('nav',-1)" @keydown.right.prevent="resizePaneByKey('nav',1)"></div>
    </aside>
    <button v-if="sidebar" class="nav-scrim" aria-label="Close navigation" @click="closeNavigation"></button>
    <main :inert="sidebar?true:undefined"><header :inert="mobileSheet?true:undefined"><button class="menu" aria-label="Open navigation" @click="openNavigation"><Menu :size="20" /></button><button class="nav-collapse" :aria-label="navCollapsed?'Expand navigation':'Collapse navigation'" :aria-pressed="navCollapsed" @click="toggleNavigation"><PanelLeftOpen v-if="navCollapsed" :size="19"/><PanelLeftClose v-else :size="19"/></button><button class="crumb" :aria-label="document?'Back to My library':undefined" :disabled="!document" @click="document&&closeDocument()"><span class="crumb-library">My library</span><ChevronRight :size="14"/><span class="crumb-document">{{document?.title||'Choose a document'}}</span></button><button class="search" @click="showSearch"><Search :size="16" /> Search workspace</button></header><p v-if="error" class="global-error">{{error}}</p>
      <div v-if="searchOpen" class="search-scrim" @click.self="closeSearch" @keydown.esc="closeSearch"><section class="search-panel" role="dialog" aria-modal="true" aria-label="Search workspace"><div class="search-field"><Search :size="18"/><input ref="searchInput" v-model="searchQuery" aria-label="Search documents, chats, and page text" placeholder="Search documents, chats, and this PDF…"><button aria-label="Close search" @click="closeSearch"><X :size="18"/></button></div><div class="search-results"><div v-if="searchedDocuments.length"><p class="search-group">DOCUMENTS</p><button v-for="item in searchedDocuments" :key="`document-${item.id}`" @click="openSearchDocument(item.id)"><FileText :size="17"/><span><strong>{{item.title}}</strong><small>{{item.page_count}} pages · {{item.filename}}</small></span></button></div><div v-if="searchedPages.length"><p class="search-group">PAGES IN {{document?.title}}</p><button v-for="item in searchedPages" :key="`page-${item.page_number}`" @click="openSearchPage(item.page_number)"><BookOpen :size="17"/><span><strong>Page {{item.page_number}}</strong><small>{{item.text.slice(0,90)}}{{item.text.length>90?'…':''}}</small></span></button></div><div v-if="searchedChats.length"><p class="search-group">CONVERSATIONS</p><button v-for="item in searchedChats" :key="`chat-${item.id}`" @click="openChat(item.id);closeSearch()"><MessageSquare :size="17"/><span><strong>{{item.title}}</strong><small>Open conversation</small></span></button></div><p v-if="!searchedDocuments.length&&!searchedPages.length&&!searchedChats.length" class="search-empty">No results for “{{searchQuery}}”</p></div></section></div>
      <section v-if="!document" class="library-view" aria-labelledby="library-title"><div class="library-heading"><div><p class="eyebrow">YOUR COLLECTION</p><h1 id="library-title">My library</h1><p>{{documents.length}} {{documents.length===1?'document':'documents'}} ready to read</p></div><label class="button primary library-upload" :aria-busy="busy" :aria-disabled="busy"><Upload :size="17" aria-hidden="true"/> {{documents.length?'Upload PDF':'Upload your first PDF'}}<span class="library-upload-status" role="status" aria-live="polite">{{busy?'Uploading PDF. Upload is temporarily unavailable.':''}}</span><input type="file" accept="application/pdf" :disabled="busy" @change="upload"></label></div><div v-if="documents.length" class="library-list"><div class="library-columns" aria-hidden="true"><span>Document</span><span>Pages</span><span>Added</span><span></span></div><ul><li v-for="item in documents" :key="item.id"><button class="library-row" @click="openDocument(item.id)"><span class="library-file-icon"><FileText :size="20" aria-hidden="true"/></span><span class="library-document"><strong>{{item.title}}</strong><small>{{item.filename}}</small></span><span class="library-pages">{{item.page_count}} pages</span><span class="library-date">{{formatDocumentDate(item.created_at)}}</span><ChevronRight class="library-chevron" :size="18" aria-hidden="true"/></button></li></ul></div><div v-else class="library-empty"><LibraryBig :size="32" aria-hidden="true"/><h2>No PDFs yet</h2><p>Upload a PDF to start reading and studying.</p></div></section>
      <template v-else><section class="title"><div><p class="eyebrow"><FileText :size="14"/> PDF DOCUMENT</p><h1>{{document.title}}</h1><small>{{document.page_count}} pages · Page {{page}} open</small></div><div class="document-actions"><button class="button ghost" @click="closeDocument"><ArrowLeft :size="16"/> Library</button><label class="button secondary"><Plus :size="16"/> New PDF<input class="hidden-input" type="file" accept="application/pdf" @change="upload"></label><button class="button study-button" :disabled="toolBusy" @click="startStudy"><BrainCircuit :size="16"/> Study this page</button><button class="button primary" @click="speak"><Volume2 :size="16"/> {{reading?'Stop':'Listen'}}</button></div></section>
      <section class="reader" :class="{'tools-closed':!toolsOpen,'mobile-tools-open':mobileSheet==='tools'}" :style="toolsOpen?{'grid-template-columns':`minmax(0, 1fr) ${toolsWidth}px`}:undefined">
        <section class="reader-main" :inert="mobileSheet?true:undefined">
          <div class="reader-bar"><button class="reader-control" :aria-pressed="thumbnailsOpen" @click="thumbnailsOpen=!thumbnailsOpen"><LibraryBig :size="16"/> Pages <span>{{document.page_count}}</span></button><div class="page-status"><span class="page-count">Page {{page}} of {{document.page_count}}</span><div class="zoom-controls" aria-label="PDF zoom controls"><button aria-label="Zoom out" :disabled="pdfZoom===75" @click="changeZoom(-10)"><ZoomOut :size="16"/></button><button class="zoom-value" aria-label="Reset zoom" title="Reset zoom" @click="pdfZoom=100">{{pdfZoom}}%</button><button aria-label="Zoom in" :disabled="pdfZoom===160" @click="changeZoom(10)"><ZoomIn :size="16"/></button><button aria-label="Reset zoom" title="Reset zoom" @click="pdfZoom=100"><RotateCcw :size="15"/></button></div></div><button class="reader-control tools-toggle" :aria-pressed="toolsOpen" @click="toolsOpen=!toolsOpen"><PanelRightClose v-if="toolsOpen" :size="17"/><PanelRightOpen v-else :size="17"/> {{toolsOpen?'Hide tools':'Show tools'}}</button></div>
          <aside v-if="thumbnailsOpen" class="rail" aria-label="Document pages"><button v-for="item in document.pages" :key="item.page_number" :aria-label="`Open page ${item.page_number}`" :class="{selected:item.page_number===page}" @click="selectPage(item.page_number)"><span></span><b>{{item.page_number}}</b></button></aside>
          <section class="pdf"><article :style="{'--pdf-zoom':pdfZoom/100}"><p class="chapter">{{document.title}}</p><h2>Page {{page}}</h2><hr><p class="document-text">{{currentText}}</p><footer>{{document.filename}} <span>{{page}}</span></footer></article></section>
          <div class="paginate"><button class="button secondary" :disabled="page===1" @click="move(-1)"><ChevronLeft :size="16"/> Previous</button><span>{{page}} / {{document.page_count}}</span><button class="button secondary" :disabled="page===document.page_count" @click="move(1)">Next <ChevronRight :size="16"/></button></div>
        </section>
        <section v-if="toolsOpen" class="tools" aria-label="Study tools" :role="mobileSheet==='tools'?'dialog':undefined" :aria-modal="mobileSheet==='tools'?true:undefined" :aria-labelledby="mobileSheet==='tools'?'tools-sheet-title':undefined" @keydown.esc="closeTools"><div class="mobile-sheet-handle" aria-hidden="true"></div><div class="pane-resizer tools-resizer" role="separator" aria-label="Resize study tools" tabindex="0" @pointerdown="resizePane('tools',$event)" @keydown.left.prevent="resizePaneByKey('tools',-1)" @keydown.right.prevent="resizePaneByKey('tools',1)"></div><div class="tools-header"><div><p class="eyebrow">PAGE {{page}}</p><strong id="tools-sheet-title">Study tools</strong></div><div class="tools-width-controls"><button aria-label="Narrower study tools" :disabled="toolsWidth<=300" @click="resizePaneByKey('tools',-1)"><ChevronRight :size="16"/></button><span>{{toolsWidth}}px</span><button aria-label="Wider study tools" :disabled="toolsWidth>=600" @click="resizePaneByKey('tools',1)"><ChevronLeft :size="16"/></button><button aria-label="Close study tools" @click="closeTools"><X :size="18"/></button></div></div><div class="tabs"><button :class="{selected:tab==='text'}" @click="tab='text'">Text</button><button :class="{selected:tab==='summary'}" @click="tab='summary'"><Sparkles :size="14"/> Summary</button><button :class="{selected:tab==='translate'}" @click="tab='translate'"><Languages :size="14"/> Translate</button><button :class="{selected:tab==='study'}" @click="tab='study'"><BrainCircuit :size="14"/> Study</button><button :class="{selected:tab==='chat'}" @click="tab='chat'"><MessageSquare :size="14"/> Chat</button></div><div class="content" v-if="tab==='text'"><div class="head"><div><p class="eyebrow">PAGE {{page}}</p><h2>Extracted text</h2></div><button class="play" aria-label="Read this page" @click="speak"><Pause v-if="reading" :size="17"/><Play v-else :size="17"/></button></div><p class="body">{{currentText}}</p><div class="tts"><Volume2 :size="19"/><span><strong>{{reading?'Reading this document':'Listen to this page'}}</strong><small>Continues page by page automatically</small></span></div></div>
          <div class="content summary-tool" v-else-if="tab==='summary'"><div class="tool-identity summary-identity"><Sparkles :size="20"/><div><p class="eyebrow">PAGE {{page}} ONLY</p><h2>Focused summary</h2></div></div><p class="body">Create a concise summary using only the page currently open on the left.</p><label>Optional focus</label><textarea v-model="summaryPrompt" placeholder="Example: Focus on the importance of database systems"></textarea><button class="button summary-action" :disabled="toolBusy" @click="summarizePage">{{toolBusy?'Summarizing…':'Summarize open page'}}</button><div v-if="summaryResult" class="tool-result summary-result"><p class="result-label">PAGE {{page}} SUMMARY</p><p>{{summaryResult}}</p></div></div>
          <div class="content translate-tool" v-else-if="tab==='translate'"><div class="tool-identity translate-identity"><Languages :size="20"/><div><p class="eyebrow">PAGE {{page}} ONLY</p><h2>Page translator</h2></div></div><p class="body">Translate the open page without changing the original document.</p><label>Target language</label><select v-model="language"><option>Luganda</option><option>Arabic</option><option>French</option><option>Swahili</option></select><button class="button translate-action" :disabled="toolBusy" @click="translatePage">{{toolBusy?'Translating…':`Translate to ${language}`}}</button><div v-if="translationResult" class="tool-result translation-result"><p class="result-label">{{language.toUpperCase()}}</p><p :dir="language==='Arabic'?'rtl':'ltr'">{{translationResult}}</p></div></div>
          <div class="content study-tool" v-else-if="tab==='study'"><div class="tool-identity study-identity"><BrainCircuit :size="20"/><div><p class="eyebrow">ACTIVE RECALL · PAGE {{page}}</p><h2>Study this page</h2></div></div><div v-if="!studyQuestion" class="study-start"><p>Generate a question from this page, answer from memory, then see what you covered and missed.</p><button class="button study-action" :disabled="toolBusy" @click="startStudy">{{toolBusy?'Preparing question…':'Start page practice'}}</button></div><template v-else><div class="question-card"><span>YOUR QUESTION</span><strong>{{studyQuestion}}</strong></div><label>Your answer</label><textarea v-model="studyAnswer" placeholder="Type what you remember from this page…"></textarea><button class="button study-action" :disabled="toolBusy||!studyAnswer.trim()" @click="checkStudyAnswer">{{toolBusy?'Checking…':'Check my answer'}}</button><div v-if="studyFeedback" class="tool-result study-result"><p class="result-label">FEEDBACK</p><p>{{studyFeedback}}</p></div></template></div>
          <div class="content chat-content" v-else><div class="head"><div><p class="eyebrow">DOCUMENT CHAT</p><h2>Ask your material</h2></div><MessageSquare :size="20"/></div><div class="messages"><p v-if="!messages.length" class="chat-empty">Ask a question. Answers are grounded in this document.</p><div v-for="(message,index) in messages" :key="index" :class="['message',message.role]">{{message.content}}</div></div><form class="composer" @submit.prevent="send"><textarea v-model="prompt" placeholder="Ask about this document…"></textarea><button class="play" :disabled="busy" aria-label="Send message"><Send :size="18"/></button></form></div></section>
        <nav class="mobile-reader-dock" :inert="mobileSheet?true:undefined" aria-label="Reader controls"><button :disabled="page===1" aria-label="Previous page" @click="move(-1)"><ChevronLeft :size="20"/><span>Previous</span></button><button aria-label="Choose page" @click="openMobileSheet('pages')"><LibraryBig :size="19"/><span>{{page}} / {{document.page_count}}</span></button><button :aria-label="reading?'Stop reading':'Listen to page'" :aria-pressed="reading" @click="speak"><Pause v-if="reading" :size="20"/><Volume2 v-else :size="20"/><span>{{reading?'Stop':'Listen'}}</span></button><button aria-label="Open study tools" @click="openMobileTools()"><Sparkles :size="20"/><span>Tools</span></button><button :disabled="page===document.page_count" aria-label="Next page" @click="move(1)"><ChevronRight :size="20"/><span>Next</span></button></nav>
        <button v-if="mobileSheet" class="sheet-scrim" aria-label="Close panel" tabindex="-1" @click="closeMobileSheet"></button>
        <section v-if="mobileSheet==='pages'" class="mobile-sheet page-sheet" role="dialog" aria-modal="true" aria-labelledby="page-sheet-title" @keydown.esc="closeMobileSheet"><div class="mobile-sheet-handle" aria-hidden="true"></div><div class="mobile-sheet-header"><div><p class="eyebrow">{{document.title}}</p><strong id="page-sheet-title">Choose a page</strong></div><button aria-label="Close page picker" @click="closeMobileSheet"><X :size="19"/></button></div><div class="mobile-page-grid"><button v-for="item in document.pages" :key="`mobile-${item.page_number}`" :class="{selected:item.page_number===page}" :aria-current="item.page_number===page?'page':undefined" @click="selectPage(item.page_number)"><FileText :size="18"/><span>Page {{item.page_number}}</span></button></div></section>
      </section></template>
    </main>
  </div>
  </div>
</template>