<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { BookOpen, ChevronLeft, ChevronRight, FileText, History, Languages, LibraryBig, LogOut, Menu, MessageSquare, Pause, Play, Plus, Search, Send, Sparkles, Upload, Volume2, X } from '@lucide/vue'
import { api, type Conversation, type DocumentDetail, type DocumentSummary, type Message, type User } from './api'

type Tab = 'text' | 'summary' | 'translate' | 'chat'
const user = ref<User | null>(null), documents = ref<DocumentSummary[]>([]), chats = ref<Conversation[]>([]), document = ref<DocumentDetail | null>(null)
const messages = ref<Message[]>([]), tab = ref<Tab>('text'), page = ref(1), reading = ref(false), sidebar = ref(false), language = ref('Luganda')
const username = ref(''), password = ref(''), authMode = ref<'login'|'register'>('login'), error = ref(''), busy = ref(false), prompt = ref(''), conversationId = ref<number|null>(null)
const currentText = computed(() => document.value?.pages.find(item => item.page_number === page.value)?.text || 'No extractable text was found on this page.')

async function refreshHistory() { documents.value = await api('/documents'); chats.value = await api('/conversations') }
async function authenticate() { busy.value=true; error.value=''; try { user.value=await api(`/auth/${authMode.value}`,{method:'POST',body:JSON.stringify({username:username.value,password:password.value})}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function logout() { await api('/auth/logout',{method:'POST'}); user.value=null; document.value=null }
async function openDocument(id:number) { document.value=await api(`/documents/${id}`); page.value=1; tab.value='text'; conversationId.value=null; messages.value=[]; sidebar.value=false }
async function upload(event:Event) { const file=(event.target as HTMLInputElement).files?.[0]; if(!file)return; busy.value=true; error.value=''; try { const data=new FormData(); data.append('file',file); const created=await api<DocumentSummary>('/documents',{method:'POST',body:data}); await refreshHistory(); await openDocument(created.id) } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function openChat(id:number) { const result=await api<{id:number;title:string;messages:Message[]}>(`/conversations/${id}`); const history=chats.value.find(item=>item.id===id); if(history?.document_id) await openDocument(history.document_id); conversationId.value=id; messages.value=result.messages; tab.value='chat'; sidebar.value=false }
async function send() { if(!prompt.value.trim())return; const content=prompt.value; messages.value.push({role:'user',content}); prompt.value=''; busy.value=true; try { const result=await api<{conversation_id:number;reply:string}>('/chat',{method:'POST',body:JSON.stringify({content,document_id:document.value?.id,conversation_id:conversationId.value})}); conversationId.value=result.conversation_id; messages.value.push({role:'assistant',content:result.reply}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
function speak() { if(reading.value){speechSynthesis.cancel();reading.value=false;return} const utterance=new SpeechSynthesisUtterance(currentText.value); utterance.onend=()=>{reading.value=false;if(document.value&&page.value<document.value.page_count){page.value++;speak()}}; reading.value=true;speechSynthesis.speak(utterance) }
function move(by:number){if(document.value)page.value=Math.min(document.value.page_count,Math.max(1,page.value+by))}
onMounted(async()=>{try{user.value=await api('/auth/me');await refreshHistory();if(documents.value[0])await openDocument(documents.value[0].id)}catch{user.value=null}})
</script>

<template>
  <section v-if="!user" class="auth-page"><form class="auth-box" @submit.prevent="authenticate"><div class="auth-brand"><b><BookOpen :size="22" /></b> edutool</div><p class="eyebrow">YOUR STUDY WORKSPACE</p><h1>{{authMode==='login'?'Welcome back':'Create your account'}}</h1><label>Username<input v-model="username" required minlength="3" autocomplete="username"></label><label>Password<input v-model="password" required minlength="8" type="password" autocomplete="current-password"></label><p v-if="error" class="error">{{error}}</p><button class="button primary auth-submit" :disabled="busy">{{busy?'Please wait…':authMode==='login'?'Sign in':'Register'}}</button><button type="button" class="auth-switch" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'New here? Create an account':'Already registered? Sign in'}}</button></form></section>
  <div v-else class="shell">
    <aside class="sidebar" :class="{open:sidebar}"><div class="brand"><b><BookOpen :size="20" /></b> edutool <button class="close" @click="sidebar=false"><X :size="19" /></button></div><label class="upload-button"><Upload :size="17" /> {{busy?'Processing…':'Upload PDF'}}<input type="file" accept="application/pdf" :disabled="busy" @change="upload"></label><nav><p class="nav-title"><LibraryBig :size="14" /> OLD DOCUMENTS</p><button v-for="item in documents" :key="item.id" :class="{active:item.id===document?.id}" @click="openDocument(item.id)"><FileText :size="16" /><span>{{item.title}}<small>{{item.page_count}} pages</small></span></button><p v-if="!documents.length" class="empty-nav">Upload your first PDF</p><p class="nav-title history-title"><History :size="14" /> CHAT HISTORY</p><button v-for="chat in chats" :key="chat.id" @click="openChat(chat.id)"><MessageSquare :size="16" /><span>{{chat.title}}</span></button><p v-if="!chats.length" class="empty-nav">No conversations yet</p></nav><nav class="bottom"><button @click="logout"><LogOut :size="17" /> Sign out</button><div class="profile"><i>{{user.username.slice(0,2).toUpperCase()}}</i><span><strong>{{user.username}}</strong><small>Student workspace</small></span></div></nav></aside>
    <main><header><button class="menu" @click="sidebar=true"><Menu :size="20" /></button><div class="crumb">My library <ChevronRight :size="14" /> {{document?.title||'Choose a document'}}</div><button class="search"><Search :size="16" /> Search notes</button></header><p v-if="error" class="global-error">{{error}}</p>
      <section v-if="!document" class="empty-library"><div><LibraryBig :size="34"/><p class="eyebrow">YOUR LIBRARY</p><h1>Bring your study material together</h1><p>Upload a PDF to extract its text, read page by page, listen aloud, and ask grounded questions.</p><label class="button primary"><Plus :size="17"/> Upload your first PDF<input type="file" accept="application/pdf" @change="upload"></label></div></section>
      <template v-else><section class="title"><div><p class="eyebrow"><FileText :size="14"/> PDF DOCUMENT</p><h1>{{document.title}}</h1><small>{{document.page_count}} pages · Saved in your library</small></div><div><button class="button secondary" @click="tab='summary'"><Sparkles :size="16"/> Study this page</button><button class="button primary" @click="speak"><Volume2 :size="16"/> {{reading?'Stop':'Listen'}}</button></div></section>
      <section class="reader"><aside class="rail"><button v-for="item in document.pages" :key="item.page_number" :class="{selected:item.page_number===page}" @click="page=item.page_number"><span></span>{{item.page_number}}</button></aside><section class="pdf"><div class="toolbar">Page {{page}} of {{document.page_count}} <span>Extracted text</span></div><article><p class="chapter">{{document.title}}</p><h2>Page {{page}}</h2><hr><p class="document-text">{{currentText}}</p><footer>{{document.filename}} <span>{{page}}</span></footer></article><div class="paginate"><button class="button secondary" @click="move(-1)"><ChevronLeft :size="16"/> Previous</button><button class="button secondary" @click="move(1)">Next <ChevronRight :size="16"/></button></div></section>
        <section class="tools"><div class="tabs"><button :class="{selected:tab==='text'}" @click="tab='text'">Text</button><button :class="{selected:tab==='summary'}" @click="tab='summary'">Summary</button><button :class="{selected:tab==='translate'}" @click="tab='translate'"><Languages :size="14"/> Translate</button><button :class="{selected:tab==='chat'}" @click="tab='chat'"><MessageSquare :size="14"/> Chat</button></div><div class="content" v-if="tab==='text'"><div class="head"><div><p class="eyebrow">PAGE {{page}}</p><h2>Extracted text</h2></div><button class="play" @click="speak"><Pause v-if="reading" :size="17"/><Play v-else :size="17"/></button></div><p class="body">{{currentText}}</p><div class="tts"><Volume2 :size="19"/><span><strong>{{reading?'Reading this document':'Listen to this page'}}</strong><small>Continues page by page automatically</small></span></div></div>
          <div class="content" v-else-if="tab==='summary'"><div class="head"><div><p class="eyebrow">SOURCE-GROUNDED</p><h2>Ask for a focused summary</h2></div><Sparkles :size="20"/></div><p class="body">Ask the AI to summarize a topic using only this uploaded document.</p><textarea v-model="prompt" placeholder="Example: Summarize the importance of database systems"></textarea><button class="button primary" :disabled="busy" @click="send();tab='chat'">Generate summary</button></div>
          <div class="content" v-else-if="tab==='translate'"><div class="head"><div><p class="eyebrow">PAGE {{page}} TRANSLATION</p><h2>Read in another language</h2></div><Languages :size="20"/></div><label>Translate English to</label><select v-model="language"><option>Luganda</option><option>Arabic</option><option>French</option><option>Swahili</option></select><button class="button primary translate-action" @click="prompt=`Translate page ${page} to ${language}`;send();tab='chat'">Translate this page</button></div>
          <div class="content chat-content" v-else><div class="head"><div><p class="eyebrow">DOCUMENT CHAT</p><h2>Ask your material</h2></div><MessageSquare :size="20"/></div><div class="messages"><p v-if="!messages.length" class="chat-empty">Ask a question. Answers are grounded in this document.</p><div v-for="(message,index) in messages" :key="index" :class="['message',message.role]">{{message.content}}</div></div><form class="composer" @submit.prevent="send"><textarea v-model="prompt" placeholder="Ask about this document…"></textarea><button class="play" :disabled="busy"><Send :size="18"/></button></form></div></section>
      </section></template>
    </main>
  </div>
</template>