<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, BookOpen, BrainCircuit, ChevronLeft, ChevronRight, FileText, History, Languages, LibraryBig, LogOut, Menu, MessageSquare, Pause, Play, Plus, Search, Send, Sparkles, Upload, Volume2, X } from '@lucide/vue'
import { api, type Conversation, type DocumentDetail, type DocumentSummary, type Message, type User } from './api'

type Tab = 'text' | 'summary' | 'translate' | 'study' | 'chat'
const user = ref<User | null>(null), documents = ref<DocumentSummary[]>([]), chats = ref<Conversation[]>([]), document = ref<DocumentDetail | null>(null)
const messages = ref<Message[]>([]), tab = ref<Tab>('text'), page = ref(1), reading = ref(false), sidebar = ref(false), language = ref('Luganda')
const username = ref(''), password = ref(''), authMode = ref<'login'|'register'>('login'), error = ref(''), busy = ref(false), prompt = ref(''), conversationId = ref<number|null>(null)
const summaryPrompt = ref(''), summaryResult = ref(''), translationResult = ref(''), studyQuestion = ref(''), studyAnswer = ref(''), studyFeedback = ref(''), toolBusy = ref(false)
const currentText = computed(() => document.value?.pages.find(item => item.page_number === page.value)?.text || 'No extractable text was found on this page.')

async function refreshHistory() { documents.value = await api('/documents'); chats.value = await api('/conversations') }
async function authenticate() { busy.value=true; error.value=''; try { user.value=await api(`/auth/${authMode.value}`,{method:'POST',body:JSON.stringify({username:username.value,password:password.value})}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function logout() { await api('/auth/logout',{method:'POST'}); user.value=null; document.value=null }
function resetPageTools() { summaryResult.value=''; translationResult.value=''; studyQuestion.value=''; studyAnswer.value=''; studyFeedback.value='' }
function closeDocument() { speechSynthesis.cancel(); reading.value=false; document.value=null; conversationId.value=null; messages.value=[]; resetPageTools() }
async function openDocument(id:number) { document.value=await api(`/documents/${id}`); page.value=1; tab.value='text'; conversationId.value=null; messages.value=[]; resetPageTools(); sidebar.value=false }
async function upload(event:Event) { const file=(event.target as HTMLInputElement).files?.[0]; if(!file)return; busy.value=true; error.value=''; try { const data=new FormData(); data.append('file',file); const created=await api<DocumentSummary>('/documents',{method:'POST',body:data}); await refreshHistory(); await openDocument(created.id) } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function openChat(id:number) { const result=await api<{id:number;title:string;messages:Message[]}>(`/conversations/${id}`); const history=chats.value.find(item=>item.id===id); if(history?.document_id) await openDocument(history.document_id); conversationId.value=id; messages.value=result.messages; tab.value='chat'; sidebar.value=false }
async function send() { if(!prompt.value.trim())return; const content=prompt.value; messages.value.push({role:'user',content}); prompt.value=''; busy.value=true; try { const result=await api<{conversation_id:number;reply:string}>('/chat',{method:'POST',body:JSON.stringify({content,document_id:document.value?.id,conversation_id:conversationId.value})}); conversationId.value=result.conversation_id; messages.value.push({role:'assistant',content:result.reply}); await refreshHistory() } catch(e){error.value=(e as Error).message} finally{busy.value=false} }
async function pageRequest(content:string) { if(!document.value) throw new Error('Open a document first'); const result=await api<{conversation_id:number;reply:string}>('/chat',{method:'POST',body:JSON.stringify({content,document_id:document.value.id,page_number:page.value})}); await refreshHistory(); return result.reply }
async function summarizePage() { toolBusy.value=true; error.value=''; try { summaryResult.value=await pageRequest(`Summarize only this page${summaryPrompt.value.trim()?` with this focus: ${summaryPrompt.value.trim()}`:''}. Give a concise heading and 3 to 5 key points.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function translatePage() { toolBusy.value=true; error.value=''; try { translationResult.value=await pageRequest(`Translate only this page into ${language.value}. Preserve meaning and formatting. Return only the translation.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function startStudy() { tab.value='study'; toolBusy.value=true; studyFeedback.value=''; studyAnswer.value=''; try { studyQuestion.value=await pageRequest('Create one recall question using only this page. Return only the question and do not reveal the answer.') } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
async function checkStudyAnswer() { if(!studyAnswer.value.trim())return; toolBusy.value=true; try { studyFeedback.value=await pageRequest(`Question: ${studyQuestion.value}\nStudent answer: ${studyAnswer.value}\nEvaluate using only this page. Give a score out of 100, correct points, missing points, and a concise improvement.`) } catch(e){error.value=(e as Error).message} finally{toolBusy.value=false} }
function speak() { if(reading.value){speechSynthesis.cancel();reading.value=false;return} const utterance=new SpeechSynthesisUtterance(currentText.value); utterance.onend=()=>{reading.value=false;if(document.value&&page.value<document.value.page_count){page.value++;speak()}}; reading.value=true;speechSynthesis.speak(utterance) }
function selectPage(nextPage:number){page.value=nextPage;resetPageTools()}
function move(by:number){if(document.value)selectPage(Math.min(document.value.page_count,Math.max(1,page.value+by)))}
onMounted(async()=>{try{user.value=await api('/auth/me');await refreshHistory();if(documents.value[0])await openDocument(documents.value[0].id)}catch{user.value=null}})
</script>

<template>
  <section v-if="!user" class="auth-page"><form class="auth-box" @submit.prevent="authenticate"><div class="auth-brand"><b><BookOpen :size="22" /></b> edutool</div><p class="eyebrow">YOUR STUDY WORKSPACE</p><h1>{{authMode==='login'?'Welcome back':'Create your account'}}</h1><label>Username<input v-model="username" required minlength="3" autocomplete="username"></label><label>Password<input v-model="password" required minlength="8" type="password" autocomplete="current-password"></label><p v-if="error" class="error">{{error}}</p><button class="button primary auth-submit" :disabled="busy">{{busy?'Please wait…':authMode==='login'?'Sign in':'Register'}}</button><button type="button" class="auth-switch" @click="authMode=authMode==='login'?'register':'login'">{{authMode==='login'?'New here? Create an account':'Already registered? Sign in'}}</button></form></section>
  <div v-else class="shell">
    <aside class="sidebar" :class="{open:sidebar}"><div class="brand"><b><BookOpen :size="20" /></b> edutool <button class="close" @click="sidebar=false"><X :size="19" /></button></div><label class="upload-button"><Upload :size="17" /> {{busy?'Processing…':'Upload PDF'}}<input type="file" accept="application/pdf" :disabled="busy" @change="upload"></label><nav><p class="nav-title"><LibraryBig :size="14" /> OLD DOCUMENTS</p><button v-for="item in documents" :key="item.id" :class="{active:item.id===document?.id}" @click="openDocument(item.id)"><FileText :size="16" /><span>{{item.title}}<small>{{item.page_count}} pages</small></span></button><p v-if="!documents.length" class="empty-nav">Upload your first PDF</p><p class="nav-title history-title"><History :size="14" /> CHAT HISTORY</p><button v-for="chat in chats" :key="chat.id" @click="openChat(chat.id)"><MessageSquare :size="16" /><span>{{chat.title}}</span></button><p v-if="!chats.length" class="empty-nav">No conversations yet</p></nav><nav class="bottom"><button @click="logout"><LogOut :size="17" /> Sign out</button><div class="profile"><i>{{user.username.slice(0,2).toUpperCase()}}</i><span><strong>{{user.username}}</strong><small>Student workspace</small></span></div></nav></aside>
    <main><header><button class="menu" @click="sidebar=true"><Menu :size="20" /></button><div class="crumb">My library <ChevronRight :size="14" /> {{document?.title||'Choose a document'}}</div><button class="search"><Search :size="16" /> Search notes</button></header><p v-if="error" class="global-error">{{error}}</p>
      <section v-if="!document" class="empty-library"><div><LibraryBig :size="34"/><p class="eyebrow">YOUR LIBRARY</p><h1>Bring your study material together</h1><p>Upload a PDF to extract its text, read page by page, listen aloud, and ask grounded questions.</p><label class="button primary"><Plus :size="17"/> Upload your first PDF<input type="file" accept="application/pdf" @change="upload"></label></div></section>
      <template v-else><section class="title"><div><p class="eyebrow"><FileText :size="14"/> PDF DOCUMENT</p><h1>{{document.title}}</h1><small>{{document.page_count}} pages · Page {{page}} open</small></div><div class="document-actions"><button class="button ghost" @click="closeDocument"><ArrowLeft :size="16"/> Library</button><label class="button secondary"><Plus :size="16"/> New PDF<input class="hidden-input" type="file" accept="application/pdf" @change="upload"></label><button class="button study-button" :disabled="toolBusy" @click="startStudy"><BrainCircuit :size="16"/> Study this page</button><button class="button primary" @click="speak"><Volume2 :size="16"/> {{reading?'Stop':'Listen'}}</button></div></section>
      <section class="reader"><aside class="rail"><button v-for="item in document.pages" :key="item.page_number" :class="{selected:item.page_number===page}" @click="selectPage(item.page_number)"><span></span>{{item.page_number}}</button></aside><section class="pdf"><div class="toolbar">Page {{page}} of {{document.page_count}} <span>Page chunk</span></div><article><p class="chapter">{{document.title}}</p><h2>Page {{page}}</h2><hr><p class="document-text">{{currentText}}</p><footer>{{document.filename}} <span>{{page}}</span></footer></article><div class="paginate"><button class="button secondary" @click="move(-1)"><ChevronLeft :size="16"/> Previous</button><button class="button secondary" @click="move(1)">Next <ChevronRight :size="16"/></button></div></section>
        <section class="tools"><div class="tabs"><button :class="{selected:tab==='text'}" @click="tab='text'">Text</button><button :class="{selected:tab==='summary'}" @click="tab='summary'"><Sparkles :size="14"/> Summary</button><button :class="{selected:tab==='translate'}" @click="tab='translate'"><Languages :size="14"/> Translate</button><button :class="{selected:tab==='study'}" @click="tab='study'"><BrainCircuit :size="14"/> Study</button><button :class="{selected:tab==='chat'}" @click="tab='chat'"><MessageSquare :size="14"/> Chat</button></div><div class="content" v-if="tab==='text'"><div class="head"><div><p class="eyebrow">PAGE {{page}}</p><h2>Extracted text</h2></div><button class="play" @click="speak"><Pause v-if="reading" :size="17"/><Play v-else :size="17"/></button></div><p class="body">{{currentText}}</p><div class="tts"><Volume2 :size="19"/><span><strong>{{reading?'Reading this document':'Listen to this page'}}</strong><small>Continues page by page automatically</small></span></div></div>
          <div class="content summary-tool" v-else-if="tab==='summary'"><div class="tool-identity summary-identity"><Sparkles :size="20"/><div><p class="eyebrow">PAGE {{page}} ONLY</p><h2>Focused summary</h2></div></div><p class="body">Create a concise summary using only the page currently open on the left.</p><label>Optional focus</label><textarea v-model="summaryPrompt" placeholder="Example: Focus on the importance of database systems"></textarea><button class="button summary-action" :disabled="toolBusy" @click="summarizePage">{{toolBusy?'Summarizing…':'Summarize open page'}}</button><div v-if="summaryResult" class="tool-result summary-result"><p class="result-label">PAGE {{page}} SUMMARY</p><p>{{summaryResult}}</p></div></div>
          <div class="content translate-tool" v-else-if="tab==='translate'"><div class="tool-identity translate-identity"><Languages :size="20"/><div><p class="eyebrow">PAGE {{page}} ONLY</p><h2>Page translator</h2></div></div><p class="body">Translate the open page without changing the original document.</p><label>Target language</label><select v-model="language"><option>Luganda</option><option>Arabic</option><option>French</option><option>Swahili</option></select><button class="button translate-action" :disabled="toolBusy" @click="translatePage">{{toolBusy?'Translating…':`Translate to ${language}`}}</button><div v-if="translationResult" class="tool-result translation-result"><p class="result-label">{{language.toUpperCase()}}</p><p :dir="language==='Arabic'?'rtl':'ltr'">{{translationResult}}</p></div></div>
          <div class="content study-tool" v-else-if="tab==='study'"><div class="tool-identity study-identity"><BrainCircuit :size="20"/><div><p class="eyebrow">ACTIVE RECALL · PAGE {{page}}</p><h2>Study this page</h2></div></div><div v-if="!studyQuestion" class="study-start"><p>Generate a question from this page, answer from memory, then see what you covered and missed.</p><button class="button study-action" :disabled="toolBusy" @click="startStudy">{{toolBusy?'Preparing question…':'Start page practice'}}</button></div><template v-else><div class="question-card"><span>YOUR QUESTION</span><strong>{{studyQuestion}}</strong></div><label>Your answer</label><textarea v-model="studyAnswer" placeholder="Type what you remember from this page…"></textarea><button class="button study-action" :disabled="toolBusy||!studyAnswer.trim()" @click="checkStudyAnswer">{{toolBusy?'Checking…':'Check my answer'}}</button><div v-if="studyFeedback" class="tool-result study-result"><p class="result-label">FEEDBACK</p><p>{{studyFeedback}}</p></div></template></div>
          <div class="content chat-content" v-else><div class="head"><div><p class="eyebrow">DOCUMENT CHAT</p><h2>Ask your material</h2></div><MessageSquare :size="20"/></div><div class="messages"><p v-if="!messages.length" class="chat-empty">Ask a question. Answers are grounded in this document.</p><div v-for="(message,index) in messages" :key="index" :class="['message',message.role]">{{message.content}}</div></div><form class="composer" @submit.prevent="send"><textarea v-model="prompt" placeholder="Ask about this document…"></textarea><button class="play" :disabled="busy"><Send :size="18"/></button></form></div></section>
      </section></template>
    </main>
  </div>
</template>